---
title: "Martingale Strategy"
author: "Connor LaChance"
date: "5/6/2021"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 1
```{r}
set.seed(123)
martingale = function(){
  # Variables
  #how many times you bet
  bet_count = 0
  
  #bet amount ($1)
  bet_amount = 1
  
  #win/lose record of each bet on red (using 1/0)
  win = 0
  lose = 0
  record = c()
  
  #money in pocket after each bet (running total)
  running_total = 100
  
  # Colors
  red = c(1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36)
  black = c(2,4,6,8,10,11,13,15,17,20,22,24,26,28,29,31,33,35)
  green = c(0)
  
  # Lists
  bet_amount_list = c()
  record_list = c()
  running_total_list = c()
  game_outcome = 0
  
  
  #While loop: won $10 or more OR you dont have enough money to make next bet
  while ((running_total - 100 < 10) && (bet_amount < running_total)){
    
    outcome = sample(0:36, 1)
    
    #if: number lands on red (18/37)
    if (is.element(outcome, red) == TRUE){
      running_total = running_total + bet_amount
      running_total_list <- c(running_total_list, running_total)
      bet_count = bet_count + 1
      win <- win + 1
      record = c("(",win, "-" , lose, ")")
      record_list <- c(record_list, record)
      bet_amount = 1
      bet_amount_list <- c(bet_amount_list, bet_amount)
    }
    
    #if: number lands on black (18/37)
    if (is.element(outcome, black) == TRUE){
      running_total = running_total - bet_amount
      running_total_list <- c(running_total_list, running_total)
      bet_count = bet_count + 1
      lose = lose + 1
      record = c("(",win, "-" , lose, ")")
      record_list <- c(record_list, record)
      bet_amount = bet_amount * 2
      bet_amount_list <- c(bet_amount_list, bet_amount)
    }
    
    #if: number lands on green (1/37)
    if (is.element(outcome, green) == TRUE){
      running_total = running_total - bet_amount
      running_total_list <- c(running_total_list, running_total)
      bet_count = bet_count + 1
      lose = lose + 1
      record = c("(",win, "-" , lose, ")")
      record_list <- c(record_list, record)
      bet_amount = bet_amount * 2
      bet_amount_list <- c(bet_amount_list, bet_amount)
    }
  }
  
  
  #final win/lose result
  record_final = c("(",win, "-" , lose, ")")
  
  
  #final balance (start with $100)
  final_balance = running_total
  
  
  #win?
  if(final_balance>=110){
    game_outcome=1 #1 for win
  }
  
  #create output
  output = list("How many times you bet" = bet_count,
                "Amount of each bet" = bet_amount_list, 
                "Win/lose record of each bet" = record_list, 
                "Money in pocket after each bet" = running_total_list, 
                "Wins" = win, "Losses" = lose, "Final balance" = final_balance,
                "Game Outcome" = game_outcome)

  output
  #return(win)
}
```


## 2
```{r warning=FALSE}
set.seed(123)
  
win_sum = c()
win_count = c()
play_time = c()
final_bal = c()
n = 100000

for (i in 1:n){
  sim = martingale()
  win_sum[i] <- sim[5]#number of bets won per game// 1
  win_count[i]<- sim[8]#number of wins and losses //2
  play_time[i] <- sim[1]#number of bets won in sim// 3
  final_bal[i] <-sim[7]#final balance for each game//4
}

#Numerical approximation for 1.
mu <- mean(as.numeric(win_sum))#average number of bets won per game
mu

#95% confidence interval for 1.
vari = var(as.numeric(win_sum))
c(mu - 1.96 * sqrt(vari/n), mu + 1.96 * sqrt(vari/n))


#Proportions of games for 2.
avg_wins = mean(as.numeric(win_count))
avg_wins
var_wins = var(as.numeric(win_count))

#confidence interval for 2.
c(avg_wins - 1.96 * sqrt(var_wins/n), avg_wins + 1.96 * sqrt(var_wins/n))

#Expected Playing Time for 3.
avg_bets=mean(as.numeric(play_time))#average number of total bets in sim
avg_bets
var_bets=var(as.numeric(play_time))#variance of total bets in sim

#95% confidence interval for 3.
c(avg_bets - 1.96 * sqrt(var_bets/n), avg_bets + 1.96 * sqrt(var_bets/n))


#Max amount can lose for 4.
100 - min(as.numeric(final_bal)) #maximum amount of money lost

```

## 3
```{r }
bet_index <- c()
balances <- c(1000)
finals<- c()

for (i in 1:1000){
  sim = martingale()
  bet_index[i] <- sim[1]
  balances[i] <- sim[4]
  finals[i] <- sim[7]
}

plot(1:as.numeric(bet_index[1]), unlist(balances[1]), type = 'l',xlim = c(1,max(as.numeric(bet_index))),ylim = c(min(unlist(balances)),max(unlist(balances))))

for (i in 2:1000){
  lines(unlist(balances[i]),col=ifelse(finals[i]==110,'blue','red'))
}


```


